 # docker-compose.yml

 version: '3'
 services:

     fdp:
         image: fairdata/fairdatapoint:1.16
         volumes:
             - ./application.yml:/fdp/application.yml:ro

     fdp-client:
         image: fairdata/fairdatapoint-client:1.16
         ports:
             - 80:80
         environment:
             - FDP_HOST=fdp

     mongo:
         image: mongo:4.0.12
         ports:
             - 27017:27017
         volumes:
             - ./mongo/data:/data/db

     blazegraph:
         image: metaphacts/blazegraph-basic
         ports:
             - 8080:8080
         volumes:
             - ./blazegraph:/blazegraph-data
